name: Build
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: mikrotik-exporter
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_IMAGE_NAME: panzelva/mikrotik-exporter
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.0"
      - name: Get version from tag
        id: version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Login to registry
        run: docker login --username panzelva --password $DOCKER_HUB_ACCESS_TOKEN
      - name: Build
        run: |
          go mod download
          go get github.com/mitchellh/gox
          go get github.com/tcnksm/ghr
          LDFLAGS="-X main.appVersion=${{ steps.version.outputs.VERSION }} -X main.shortSha=$GITHUB_SHA"
          CGO_ENABLED=0 gox -os="linux freebsd netbsd" -arch="amd64 arm arm64 386" -parallel=4 -ldflags "$LDFLAGS" -output "dist/${APP_NAME}_{{.OS}}_{{.Arch}}"
          ghr -t ${{ secrets.GITHUB_TOKEN }} -replace ${{ steps.version.outputs.TAG }} dist/
          docker build -t $DOCKER_IMAGE_NAME:${{ steps.version.outputs.VERSION }} .
          docker push $DOCKER_IMAGE_NAME:${{ steps.version.outputs.VERSION }}
